BASF-Mobile-Solutions/basf_flutter_components

.github/workflows/ci.yaml
CHANGELOG.md
lib/src/theme/inputs.dart
lib/src/theme/themes.dart
lib/src/widgets/buttons/basf_button.dart
lib/src/widgets/buttons/outlined_button.dart
lib/src/widgets/buttons/text_button.dart
lib/src/widgets/options/dropdown_input.dart
pubspec.yaml
test/src/widgets/options/dropdown_test.dart
test/src/widgets/spacers_test.dart

Fixed some styles on the theming buttons and textfields

fix: styles, v2.1.2

---

CHANGELOG.md
example/pubspec.lock
lib/src/widgets/options/radio.dart
pubspec.yaml

fix: Fixed radio buttons identity check

---

CHANGELOG.md
example/lib/screens/forms/text_field.dart
example/pubspec.lock
lib/src/widgets/options/dropdown_input.dart
pubspec.yaml

fix: Dropdown

---

.github/workflows/ci.yaml
.github/workflows/publish.yaml
CHANGELOG.md
example/pubspec.lock
example/pubspec.yaml
lib/src/widgets/buttons/outlined_button.dart
lib/src/widgets/options/dropdown_input.dart
pubspec.lock
pubspec.yaml

feat: Dropdown loading changed

---

CHANGELOG.md
example/pubspec.lock
lib/src/widgets/inputs/text_field.dart
pubspec.yaml

Changed the title style of TextInput

style: changed the title style of TextInput

---

CHANGELOG.md
lib/src/widgets/animations/fade.dart
pubspec.yaml

Fade had memory leak, fixed it by disposing animation controller on dispose.

fix: fade memory leak

---

.github/workflows/ci.yaml
CHANGELOG.md
CONTRIBUTING.md
example/ios/Runner.xcodeproj/project.pbxproj
example/ios/Runner/Info.plist
example/lib/main.dart
example/lib/screens/fonts/fonts.dart
example/pubspec.lock
lib/src/theme/buttons.dart
lib/src/theme/inputs.dart
lib/src/theme/themes.dart
lib/src/widgets/dialogs.dart
lib/src/widgets/inputs/text_field.dart
lib/src/widgets/options/dropdown_input.dart
lib/src/widgets/options/option_button.dart
lib/src/widgets/options/radio.dart
pubspec.lock
pubspec.yaml
test/src/theme/themes_test.dart
test/src/widgets/animations/fade_test.dart
test/src/widgets/buttons/outlined_button_test.dart
test/src/widgets/buttons/slider_button_test.dart
test/src/widgets/buttons/text_button_test.dart

Updated versions and deprecated fields to fit Flutter 3.7 and Dart 2.19

perf: Flutter 3.7 and Dart 2.19

---

.github/workflows/publish.yaml

ci: Update publish.yaml

---

example/analysis_options.yaml
example/pubspec.yaml

fix: analysis

---

.github/workflows/ci.yaml
.github/workflows/publish.yaml
CHANGELOG.md
example/pubspec.lock
example/pubspec.yaml
lib/src/widgets/inputs/text_field.dart
pubspec.lock
pubspec.yaml

Fixed an error that was thrown after the input filed was disposed
- [x ] 🛠️ Bug fix (non-breaking change which fixes an issue)

fix: Fixed an error that was thrown after the input filed was disposed

---

example/lib/screens/forms/options.dart
example/lib/screens/themes/themes.dart

fix: lint errors

---

.github/workflows/ci.yaml
.github/workflows/publish.yaml
CHANGELOG.md
example/pubspec.lock
example/pubspec.yaml
lib/src/theme/themes.dart
lib/src/widgets/options/checkboxes.dart
pubspec.lock
pubspec.yaml

perf: update to dart 3

---

CHANGELOG.md

fix: redeploy

---

.github/workflows/ci.yaml
.github/workflows/publish.yaml
CHANGELOG.md
example/android/app/build.gradle
example/android/build.gradle
example/android/gradle.properties
example/android/gradle/wrapper/gradle-wrapper.properties
example/ios/Runner.xcodeproj/project.pbxproj
example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
example/lib/screens/animations/animations.dart
example/pubspec.lock
example/pubspec.yaml
pubspec.lock
pubspec.yaml
test/src/widgets/spacers_test.dart

Flutter 3.13.6
Dart 3.1.3
Gradle 8

perf: update flutter, dart, gradle

---

.github/workflows/ci.yaml
.github/workflows/publish.yaml
CHANGELOG.md
example/pubspec.lock
example/pubspec.yaml
lib/src/theme/themes.dart
lib/src/widgets/options/radio.dart
pubspec.lock
pubspec.yaml

feat: update flutter, remove material 2

---

CHANGELOG.md
example/lib/screens/animations/animations.dart
example/lib/screens/dialogs/dialogs_overview.dart
example/lib/screens/themes/themes.dart
example/pubspec.lock
lib/src/theme/themes.dart
lib/src/widgets/options/dropdown_input.dart
pubspec.yaml

feat: update theme

---

.github/workflows/ci.yaml
.github/workflows/publish.yaml
CHANGELOG.md
example/.metadata
example/android/app/build.gradle
example/android/app/src/main/AndroidManifest.xml
example/android/build.gradle
example/android/settings.gradle
example/ios/Runner.xcodeproj/project.pbxproj
example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
example/pubspec.lock
example/pubspec.yaml
lib/src/widgets/inputs/text_field.dart
lib/src/widgets/options/radio.dart
pubspec.lock
pubspec.yaml

feat: Flutter 3.19

---

CHANGELOG.md
lib/src/widgets/inputs/persisted_text_field.dart
pubspec.yaml

feat: update show up of persistent input

---

.github/workflows/ci.yaml
.github/workflows/publish.yaml
CHANGELOG.md
example/android/gradle/wrapper/gradle-wrapper.properties
example/android/settings.gradle
example/pubspec.lock
example/pubspec.yaml
lib/basf_flutter_components.dart
lib/src/widgets/inputs/logic/persisted_data.dart
lib/src/widgets/inputs/logic/persisted_input_cubit.dart
lib/src/widgets/inputs/persisted_text_field.dart
pubspec.lock
pubspec.yaml

Persistent update widget data to be available from outside of the widget

feat: Pers update

---

.github/workflows/ci.yaml
.github/workflows/publish.yaml
CHANGELOG.md
example/android/gradle/wrapper/gradle-wrapper.properties
example/android/settings.gradle
example/pubspec.lock
example/pubspec.yaml
lib/src/theme/buttons.dart
lib/src/widgets/buttons/basf_button.dart
lib/src/widgets/inputs/text_field.dart
pubspec.lock
pubspec.yaml

feat: flutter 3.22 update

---

CHANGELOG.md
lib/src/theme/themes.dart
pubspec.yaml

fix: Adds NotoSans as fallback

---

.github/workflows/ci.yaml
.github/workflows/publish.yaml
CHANGELOG.md
analysis_options.yaml
example/pubspec.lock
lib/src/widgets/inputs/text_field.dart
pubspec.lock
pubspec.yaml

fix dart 3.5

---

CHANGELOG.md
example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
example/lib/screens/forms/options.dart
example/pubspec.lock
lib/basf_flutter_components.dart
lib/src/widgets/layout/label.dart
lib/src/widgets/options/dropdown_input.dart
pubspec.yaml

Fixed an overflow issue in dropdown.

fix: Dropdown update

---

CHANGELOG.md
lib/src/widgets/inputs/text_field.dart
pubspec.yaml

- small fix and update changelog

fix: Textfield and update changelog

---

.github/workflows/ci.yaml
.github/workflows/publish.yaml
CHANGELOG.md
example/lib/screens/forms/text_field.dart
example/pubspec.lock
lib/src/theme/inputs.dart
lib/src/widgets/inputs/text_field.dart
lib/src/widgets/layout/label.dart
pubspec.lock
pubspec.yaml

fix: Theme update

---

CHANGELOG.md
lib/src/dto/text_field_data.dart
lib/src/widgets/inputs/persisted_text_field.dart
lib/src/widgets/inputs/text_field.dart
pubspec.yaml

- Add function to TextFieldData, to set the controller text to the favorite value of persisted input
- Add greyWhenDisabled attribute to BasfTextField, to show or hide the grey color when disabled

feat: Improve usage of BasfTextField;

---

CHANGELOG.md

fix: update CHANGELOG.md
